apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: company-matching
  name: company-matching
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 60
  selector:
    matchLabels:
      app: company-matching
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: company-matching
    spec:
      containers:
        - image: staillansag/msr-company-matching:latest
          imagePullPolicy: Always
          name: company-matching-msr
          ports:
            - name: metrics
              containerPort: 5555
          env:
            - name: SAG_IS_CONFIG_PROPERTIES
              value: /opt/softwareag/IntegrationServer/packages/CompanyMatching/application.properties  
            - name: SERVER_LOCATION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DATASOURCE_CLASS
              value: com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: company-matching-secrets
                  key: databaseUser
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: company-matching-secrets
                  key: databasePassword
            - name: DB_SERVERNAME
              valueFrom:
                configMapKeyRef:
                  name: company-matching-config
                  key: databaseServerName
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: company-matching-config
                  key: databaseServerPort
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: company-matching-config
                  key: databaseName
            - name: IO_INT_URL
              valueFrom:
                configMapKeyRef:
                  name: company-matching-config
                  key: wmioIntegrationUrl
            - name: IO_INT_USER
              valueFrom:
                secretKeyRef:
                  name: company-matching-secrets
                  key: wmioIntegrationUser
            - name: IO_INT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: company-matching-secrets
                  key: wmioIntegrationPassword
          livenessProbe:
            tcpSocket:
              port: 5555
            initialDelaySeconds: 180
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 5555
            initialDelaySeconds: 5
            periodSeconds: 15
            failureThreshold: 12
